version: '3.14'
services:
  set-volume-owner:
    image: alpine
    command: chown -R 10001:10001 /app/data
    volumes:
      - rauthy:/app/data

  rauthy:
    image: ghcr.io/sebadob/rauthy:0.23.0-lite
    depends_on:
      - set-volume-owner
    environment:
      PUB_URL: localhost:5173
      DATABASE_URL: 'sqlite:/app/data/rauthy.db'
      BOOTSTRAP_ADMIN_EMAIL: admin@localhost.de
      BOOTSTRAP_ADMIN_PASSWORD_PLAIN: adminadmin
      COOKIE_MODE: danger-insecure
      COOKIE_SET_PATH: false
    ports:
      - 8921:8080
    volumes:
      - rauthy:/app/data

volumes:
  rauthy:
