version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:15.5-bullseye
    restart: always
    volumes:
       - ./data/postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  redis:
    container_name: redis
    image: redis:7.0.15-bookworm
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis-data:/data

  pgweb:
    container_name: pgweb
    image: sosedoff/pgweb:0.14.1
    restart: always
    ports:
      - '3006:8081'
    environment:
      - PGWEB_DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
    depends_on:
      - postgres

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - "3007:8081"

  maildev:
      container_name: maildev
      image: maildev/maildev
      restart: always
      ports:
        - "1080:1080"
        - "1025:1025"