version: '3.14'
services:
  smtp4dev:
    image: rnwood/smtp4dev
    ports:
      - '8091:80'
      - '2525:25'

  set-rauthy-volume-owner:
    image: alpine
    command: chown -R 10001:10001 /app/data
    volumes:
      - rauthy:/app/data

  rauthy:
    image: ghcr.io/sebadob/rauthy:0.23.4-lite
    depends_on:
      - set-rauthy-volume-owner
      - smtp4dev
    environment:
      PUB_URL: localhost:9523
      DATABASE_URL: 'sqlite:/app/data/rauthy.db'
      BOOTSTRAP_ADMIN_EMAIL: admin@localhost.de
      BOOTSTRAP_ADMIN_PASSWORD_PLAIN: adminadmin
      COOKIE_MODE: danger-insecure
      COOKIE_SET_PATH: false
      SMTP_URL: smtp4dev
      SMTP_DANGER_INSECURE_PORT: 25
      SMTP_USERNAME: dummy
      SMTP_PASSWORD: dummy
      SMTP_FROM: rauthy@localhost.de
      SMTP_DANGER_INSECURE: true
      BOOTSTRAP_API_KEY: ewoJIm5hbWUiOiAidXNlcmF0dHJpYnV0ZXMiLAoJImFjY2VzcyI6IFsKCQl7CgkJCSJncm91cCI6ICJVc2VyQXR0cmlidXRlcyIsCgkJCSJhY2Nlc3NfcmlnaHRzIjogWyJyZWFkIiwgImNyZWF0ZSIsICJ1cGRhdGUiLCAiZGVsZXRlIl0KCQl9CgldCn0K
      BOOTSTRAP_API_KEY_SECRET: very_bad_secret_use_only_in_development_qH6udD97p1hEXOxqFWoZwxAjl
      EMAIL_SUB_PREFIX: Weird.One
    ports:
      - 8921:8080
    volumes:
      - rauthy:/app/data

volumes:
  rauthy:
