version: '3.8'

services:
  postgres:
    image: postgres:15.5-bullseye
    volumes:
       - ./data/postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  pgweb:
    image: sosedoff/pgweb:0.14.1
    restart: always
    ports:
      - '3006:8081'
    environment:
      - PGWEB_DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
    depends_on:
      - postgres

  maildev:
      image: maildev/maildev
      ports:
        - "1080:1080"
        - "1025:1025"